services:
  postgres:
    image: postgres:18-alpine
    platform: linux/x86_64
    container_name: mecanizou_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mecanizou
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    platform: linux/x86_64
    container_name: mecanizou_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:8-alpine
    container_name: mecanizou_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data
    command: redis-server --appendonly yes

  redisinsight:
    image: redis/redisinsight:latest
    container_name: mecanizou_redisinsight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - ./.data/redisinsight:/data
    environment:
      RI_ACCEPT_TERMS_AND_CONDITIONS: "true"
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: "6379"
      RI_REDIS_ALIAS: "mecanizou-redis"
    depends_on:
      - redis

networks:
  default:
    driver: bridge